### ISSUE TITLE
Problema al crear prueba de guía de despacho

### ISSUE THREAD

**Issue by GonzaloSaavedraM** [chilesystems/samples-dte#1]
AL crear intentar crear una prueba de guía de despacho se genera el siguiente error:
![image](https://user-images.githubusercontent.com/44876848/48217166-cc1a0d80-e36d-11e8-9c41-b4ff629f05fa.png)

-la prueba es en base al siguiente caso
[SIISetDePruebas995934302.txt](https://github.com/chilesystems/samples-dte/files/2562914/SIISetDePruebas995934302.txt)

**Comment by chilesystems** [comment]
Recuerda que el certificado digital debe estar instalado en la máquina. ¿Verificaste el nombre con el que lo estás llamando?.

No está indicado aún, pero dentro de tu carpeta Debug o Release según corresponda, debes tener una carpeta con nombre "out" y dentro, otras dos con nombres "temp" y "caf". 

Actualizaré pronto la documentación.

**Comment by GonzaloSaavedraM** [comment]
tengo instalado el certificado en el equipo, El nombre con el que lo estoy llamando es el que me muestra el SII.

Las carpetas ya las tengo creadas
![image](https://user-images.githubusercontent.com/44876848/48218991-68deaa00-e372-11e8-9623-b5a4a6407fd6.png)

**Comment by GonzaloSaavedraM** [comment]
Estimado, ya encontré un problema y era el nombre del certificado, había que poner el nombre descriptivo, lo hice y ahora no me genera el error.
![image](https://user-images.githubusercontent.com/44876848/48220047-629dfd00-e375-11e8-9488-6d904d5415fa.png)
Pero aún no me genera el archivo con el prefijo DTE_XXXXXXXXXXX y al momento de Generar el sobre de envío me muestra el siguiente error.
![image](https://user-images.githubusercontent.com/44876848/48220153-b0b30080-e375-11e8-9da1-9f5c655320d3.png)

**Comment by chilesystems** [comment]
Gonzalo, la misma excepción te indica los errores para que los verifiques.
