### ISSUE TITLE
Problemas con Certificado en IIS

### ISSUE THREAD

**Issue by ccerdaz** [chilesystems/samples-dte#3]
Tengo un problema al utilizar la API con una aplicación WEB instalada en un IIS.
La descripción del problema es que al momento de firmar un DTE, se genera el error "_Referencia a objeto no establecida como instancia de un objeto_", (lo que no ayuda mucho).
El error se produce en la línea:

`return dte.Firmar(nombreCertificado, serialKEY, pathResult);`

Como antecedente, al ejecutar el proyecto en modo debug, el error NO se produce y por eso me extraña más!

Para indagar un poco más, creé una aplicación donde extraigo todos los Certificados instalados en mi máquina y los muestro en un Label.
`X509Certificate2 _X509Cert = new X509Certificate2();
 X509Store store = new X509Store("MY", StoreLocation.CurrentUser);
 store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
 X509Certificate2Collection collection = (X509Certificate2Collection)store.Certificates;`

Al hacerlo en modo debug, me muestra el certificado que tengo instalado pero al correrlo en el IIS **no me muestra ninguno**.
Luego cambié de **CurrentUser** a **LocalMachine** y ahora sí que me muestra el certificado cuando lo corro en el IIS.

Me da la idea que la API debe estar haciendo lo mismo. Va a buscar el/los certificados instalados en CurrentUser pero no en el LocalMachine, lo que imposibilita poder usarla en una aplicación WEB.

**Comment by chilesystems** [comment]
Hola!, Gracias por el reporte.

Se ha actualizado la API. Ahora esta busca el certificado digital en ambos repositorios (CurrentUser y LocalMachine).

**Comment by ccerdaz** [comment]
Ok, gracias.
