### ISSUE TITLE
Tamaño de imagen del Timbre en aplicación WEB

### ISSUE THREAD

**Issue by ccerdaz** [chilesystems/samples-dte#4]
Tengo problemas al obtener la imagen del timbre cuando uso la API en un proyecto WEB.
Cuando lo hago con la aplicación de escritorio **SIMPLEAPI_Demo** me queda de un tamaño **307x153** píxeles pero cuando lo hago con mi aplicación me queda de un tamaño más pequeño (**120x72** pixeles) y que no se puede interpretar con ningún lector de timbres como el de e-Factura.
El tamaño de la imagen ya viene definido al des-serializar el DTE, por lo tanto no se trataría de un tema del pictureBox, es decir, el tamaño viene directamente desde dte.Documento.TimbrePDF417.**Height** y dte.Documento.TimbrePDF417.**Width**.

**Comment by chilesystems** [comment]
Hola,

Se ha actualizado el .dll, solucionando el problema de la generación del timbre pequeño en aplicaciones web.

Sólo tienes que reemplazar el .dll de tu proyecto por el nuevo que ya se encuentra disponible en http://www.chilesystems.com/SDK/SIMPLE_SDK.dll

Saludos.
