### ISSUE TITLE
Cesion

### ISSUE THREAD

**Issue by Cesar250101** [chilesystems/samples-dte#5]
Hola Gonzalo, estoy tratando de generar el xml de la cesión de un xml que descargue de mi sistema, pero me parece el siguiente error:

 No se esperaba <EnvioDTE>, adjunto imagen
![cesion](https://user-images.githubusercontent.com/27635705/70873069-8ffea680-1f8a-11ea-8159-d18de6af82ac.png)

Trate de hacer el cambio que  indica este comentario del código pero no se donde ni que código poner.

La cesión se debe realizar a partir de un DTE existente
                 Para ello, se carga el correspondiente XML. Puede ser un <EnvioDTE> o <DTE>,
                 Sin embargo, al usar el primero, hay que hacer la respectiva modificación 
                 de Tipo en XmlHandler.DeserializeFromString<T>*/

por favor si me puedes ayudar.

**Comment by chilesystems** [comment]
Hola Cesar,

El error indica que le estás pasando un EnvioDTE y el deserializador no se lo esperaba. 

Si le estás pasando un DTE, el tipo <T> debería ser ChileSystems.DTE.Engine.Documento.DTE, no EnvioDTE.

Si le estás pasando un EnvioDTE, el tipo <T> debería ser ChileSystems.DTE.Engine.Envio.EnvioDTE, no DTE. Deberás usar el método DeserializeFromString como se indica en los comentarios del código.

Saludos.

**Comment by Cesar250101** [comment]
Hola Gonalo, ahora me dice que el tipo dte no corresponde, te puedo enviar el xml para que hagas una prueba?.

[cid:46949b2f-ec3b-4a50-ae6d-a96a51762445]


Cesar A. Ocampo M.


________________________________
De: Gonzalo Bustamante Bañados <notifications@github.com>
Enviado: lunes, 16 de diciembre de 2019 12:02
Para: chilesystems/samples-dte <samples-dte@noreply.github.com>
Cc: Cesar A. Ocampo M. <cesar250101@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [chilesystems/samples-dte] Cesion (#5)


Hola Cesar,

El error indica que le estás pasando un EnvioDTE y el deserializador no se lo esperaba.

Si le estás pasando un DTE, el tipo debería ser ChileSystems.DTE.Engine.Documento.DTE, no EnvioDTE.

Si le estás pasando un EnvioDTE, el tipo debería ser ChileSystems.DTE.Engine.Envio.EnvioDTE, pero deberás usar el método DeserializeFromString como se indica en los comentarios del código.

Saludos.

**Comment by chilesystems** [comment]
César,

Debes indicarme el error que te está generando y toda la información posible para detectar la falla.

Saludos.
