### ISSUE TITLE
Soporte a Net Core

### ISSUE THREAD

**Issue by theangel1** [chilesystems/samples-dte#7]
Estimados, piensan dar soporte a net core? Al usar entorno net core  el metodo de firma falla porque usa sha256 (deberia ser sha1), esto tiene que ver con que en entornos net framework se usa  RSACryptoServiceProvider versus lo nuevo de net core que es RSACng.
Desde ya, gracias por la respuesta.
Adjunto imagen y link de referencia.
![Untitled](https://user-images.githubusercontent.com/28565354/104652585-13ac2a80-5698-11eb-9ceb-d77fb6d82158.png)

https://www.pkisolutions.com/accessing-and-using-certificate-private-keys-in-net-framework-net-core/

**Comment by chilesystems** [comment]
Hola, aún no contamos con soporte para .net core.
