### ISSUE TITLE
Digital signature algorithm changed to RSASHA256 suddenly

### ISSUE THREAD

**Issue by SeniorDev1122** [chilesystems/samples-dte#8]
I have a problem the issue in my ASP.net core, First time it is working very well, but Currently I'm a getting some issue.
When i sign using simple api, it signed with RSASHA256. At first time it signed with RSASHA1 on my app.
Does anybody have an similar experience?

**Comment by chilesystems** [comment]
Thats because this API only works on NET Framework. Next week we will release .net core version.
